### ISSUE TITLE
How to run fully raw SQL?

### ISSUE THREAD

**Issue by garmoshka-mo** [sutandojs/sutando#15]
E.g. "SET TIME ZONE 'UTC';"
No obvious way to do it

**Comment by kiddyuchina** [comment]
To run fully raw SQL queries, you can use the raw() method like:
```js
const connection = sutando.connection();
const res = await connection.raw("SET TIME_ZONE = ?", 'UTC');
```
That the response will be whatever the underlying sql library would typically return on a normal query

**Comment by garmoshka-mo** [comment]
thank you, it works 💪 would be good to have it in docs, in my experience orm is great, but its often case when full raw sql is needed

**Comment by kiddyuchina** [comment]
Already added 😄
https://sutando.org/guide/query-builder.html#running-sql-queries
