### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by Salmondx** [sutandojs/sutando#38]
Hello! Thanks for this great project, ORM like this was heavily missed in the js ecosystem and it's great that you built it.

Do you have any performance benchmarks by any chance? Nodejs ecosystem likes to compare libraries to one another and I was curious if runtime magic that you do (with scopes, relations, mutators and etc) affects performance in any significant manner.

Thank you again and can't wait to start using it in my next project.

**Comment by kiddyuchina** [comment]
Hey! Thank you for your love! 😊

I built a benchmark repository at https://github.com/kiddyuchina/simple-orm-benchmark. It's pretty simple for now, I'll add more examples over time. If you are curious, you can check it out!

If you have any additional questions or comments, please feel free to contact me.

**Comment by Salmondx** [comment]
awesome, tyvm, exactly what I'd like to see!
