### ISSUE TITLE
would it be possible to add native MariaDB driver?

### ISSUE THREAD

**Issue by benjaminv** [sutandojs/sutando#5]
I'm on a similar boat with [this man](https://wildwolf.name/mariadb-driver-for-knex/). Since #sutando is based on #knex, I am wondering how easy would it be possible to implement similar (or same) to sutando please. 
Any suggestion, idea, inspiration would be highly appreciated.

**Comment by benjaminv** [comment]
Update: interesting it seems #MariaDB is implementing this from their connector https://jira.mariadb.org/projects/CONJS/issues/CONJS-264

**Comment by kiddyuchina** [comment]
Can you give a specific example of Knex using the mariadb connector?
In fact, I don’t know much about the functions of mariadb connector. Is there anything that mysql/mysql2 can't do?

**Comment by benjaminv** [comment]
Thanks for responding. I don't feel there is much that mysql/mysql2 won't be able to archive with MariaDB just my project has already implemented [mariadb connector](https://www.npmjs.com/package/mariadb) for Node.js. It would be really nice to avoid alteration and keep it native too. I will have another look and see if this is something that i can get it in.

**Comment by kiddyuchina** [comment]
If you just want to use mariadb connector, I tried this [library](https://github.com/sjinks/knex-mariadb) and it works. Here is a simple example:
```bash
$ pnpm add knex-mariadb mariadb
```

```js
const { sutando } = require('sutando');
const mdb = require('knex-mariadb');

sutando.addConnection({
  client: mdb,
  connection: {
    host: 'localhost',
    user: 'username',
    password: 'password',
    database: 'database',
  }
});

// ...
```
