### ISSUE TITLE
How do I include ID, when returning models?

### ISSUE THREAD

**Issue by Julius-Bendt** [sutandojs/sutando#58]
I have a user model defined as:

```ts
export class User extends Model {
    protected table: string = "users";
    protected primaryKey: string = "id";

    id!: string;
    name!: string;
    email!: string;
    password!: string;

    hidden: string[] = ["password"];

    toJSON() {
        return {
            id: this.id,
            name: this.name,
        }
    }
(...)
```

Is it possible to include the id, when returning the model via express, without using the ToJson function? 

I expected everything but the items in "hidden" to be returned

I've tested with two models - including the one above, both missing ids when returned via http routes

**Comment by kiddyuchina** [comment]
In fact, you don't need to define the `toJSON` method, you can directly use the model instance
```typescript
const user = await User.query().first();
res.json(user);
```
Here is an example using typescript+express to see if it can solve your problem.

https://github.com/sutandojs/sutando-examples/tree/main/typescript/rest-express

**Comment by Julius-Bendt** [comment]
My problem was that "id" was returned as null, most likely because they were mapped wrong due to not being a int but a string

Adding these two:
```ts
(...) Model (...)
keyType = 'string';
incrementing = false;
```
fixed the problem
