### ISSUE TITLE
Missing compose in typescript

### ISSUE THREAD

**Issue by Julius-Bendt** [sutandojs/sutando#61]
I tried implementing as per the docs, however "compose" is not defined in sutando.
https://sutando.org/guide/models.html#soft-deleting

![image](https://github.com/user-attachments/assets/9f6323ca-a658-4989-9cbd-c344c1ecb6e6)

I'm using the latest version, 1.6.4

**Comment by kiddyuchina** [comment]
It has been resolved in v1.6.5. 😀
