### ISSUE TITLE
No typescript support

### ISSUE THREAD

**Issue by sacsbrainz** [sutandojs/sutando#7]
when will typescript support be added?

**Comment by jjjrmy** [comment]
this would be good for the roadmap

**Comment by kiddyuchina** [comment]
we're working hard to bring typescript support, and we're aiming to have the initial implementation ready by February.

**Comment by jjjrmy** [comment]
@kiddyuchina will this include module imports instead of require?

**Comment by kiddyuchina** [comment]
I'm pleased to announce that we've added TypeScript support in #18.
Feel free to test it out and let us know if you encounter any issues. We appreciate your support and feedback.

**Comment by SDIjeremy** [comment]
Amazing, can’t wait to try!
