### ISSUE TITLE
having a discord server would be nice

### ISSUE THREAD

**Issue by sacsbrainz** [sutandojs/sutando#8]
a place where we could be in touch with dev and ask questions if the need arise

**Comment by jjjrmy** [comment]
issues or discussion here might be fine, the maintainer seems very responsive to issues already.
I don't know if there'd be enough members to warrant maintaining Discord server, as nice as that would be.

**Comment by kiddyuchina** [comment]
while we don't have any additional platforms at the moment, you can raise your questions or issues directly on Issues. as @jjjrmy mentioned, we're actively monitoring and addressing them there.
